### PR TITLE
bug #399: fixed spam to group captain

### LINKED ISSUE #399: [BUG] Sending as many messages as sending requests
**Preconditions:**
- Existing account;
- No group membership.

**Steps to reproduce**
1. Create account;
2. Click on avatar;
3. Click on 'Групи';
4. Choose group;
5. Click on 'Надіслати запит'.

**Actual result:**
Receiver(starosta) gets as many messages in telegram as I've sent requests, therefore I can just spam him.

**Environment:**
Prod.

**Possible solution**
Create new status for request, for example it could be something like "очікує відповіді".

### PR DESCRIPTION
**Pull request by bohdanbulakh**
- added check for PENDING status of the group join request
- created custom exception for this

closes #399

### CODE REVIEW

File: fictadvisor-api/src/v2/utils/exceptions/AlreadySendGroupRequestException.ts [hunk 1]
```diff
@@ -0,0 +1,7 @@
+import { HttpException, HttpStatus } from '@nestjs/common';
+
+export class AlreadySendGroupRequestException extends HttpException {
+  constructor () {
+    super('You have already send request to join this group', HttpStatus.BAD_REQUEST);
```
Comment (VlO-OlV) [inline fictadvisor-api/src/v2/utils/exceptions/AlreadySendGroupRequestException.ts:5]: Grammar mistake: "You have already _sent_"

File: fictadvisor-api/src/v2/api/services/UserService.ts [hunk 2]
```diff
@@ -263,9 +264,15 @@ export class UserService {
 
   async requestNewGroup (id: string, { groupId, isCaptain }: GroupRequestDTO) {
     const student = await this.studentRepository.findById(id);
-    if (student.state === State.APPROVED) {
+
+    switch (student.state) {
+    case State.APPROVED: {
```
Comment (VlO-OlV) [inline fictadvisor-api/src/v2/api/services/UserService.ts:269]: Add indentation for case blocks

**Review by VlO-OlV — CHANGES_REQUESTED** [review]

File: fictadvisor-api/src/v2/api/services/UserService.ts (hunk 2 above)
Comment (bohdanbulakh) [reply fictadvisor-api/src/v2/api/services/UserService.ts:269]: I tried to do this, but eslint highlights it as error

**Review by VlO-OlV — APPROVED** [review]
