### PR TITLE
bug #296: fixed bugs in update event endpoint

### LINKED ISSUE #296: [BUG] Fix some bugs in update event endpoint
PrismaClientKnownRequestError:  Invalid `prisma.event.update()` invocation:

Unique constraint failed on the fields: (`event_id`,`discipline_type_id`)
    at Rn.handleRequestError (/app/index.js:55921:7325)
    at Rn.handleAndLogRequestError (/app/index.js:55921:6754)
    at Rn.request (/app/index.js:55921:6344)
    at async ScheduleService.updateEvent (/app/index.js:466912:9)
    at async ScheduleController.update (/app/index.js:450251:9)

PrismaClientKnownRequestError: Invalid prisma.disciplineTeacherRole.create() invocation:

Unique constraint failed on the fields: (discipline_teacher_id,discipline_type_id,role)
at Rn.handleRequestError (/app/index.js:55921:7325)
at Rn.handleAndLogRequestError (/app/index.js:55921:6754)
at Rn.request (/app/index.js:55921:6344)
at async ScheduleService.prepareDiscipline (/app/index.js:466985:17)
at async ScheduleService.updateDiscipline (/app/index.js:466927:9)
at async ScheduleService.updateEvent (/app/index.js:466911:28)
at async ScheduleController.update (/app/index.js:450251:9)

PrismaClientKnownRequestError: Invalid prisma.discipline.update() invocation:

The records for relation DisciplineToDisciplineType between the Discipline and DisciplineType models are not connected.
at Rn.handleRequestError (/app/index.js:55921:7325)
at Rn.handleAndLogRequestError (/app/index.js:55921:6754)
at Rn.request (/app/index.js:55921:6344)
at async ScheduleService.clearDiscipline (/app/index.js:466963:13)
at async ScheduleService.updateDiscipline (/app/index.js:466925:13)
at async ScheduleService.updateEvent (/app/index.js:466911:28)
at async ScheduleController.update (/app/index.js:450251:9)

### PR DESCRIPTION
**Pull request by VlO-OlV**
- fixed some bugs in update event endpoint

closes #296

### CODE REVIEW

File: fictadvisor-api/src/v2/api/services/ScheduleService.ts [hunk 1]
```diff
@@ -457,12 +457,8 @@ export class ScheduleService {
     const data = await this.eventRepository.find({
       id: eventId,
     });
-    if (data.eventInfo) {
-      for (const eventInfo of data.eventInfo) {
-        if (eventInfo.number === index) {
-          return true;
-        }
-      }
+    if (data.eventInfo && some(data.eventInfo, "number", index)) {
```
Comment (dmykyr) [inline fictadvisor-api/src/v2/api/services/ScheduleService.ts:460]: You can simplify this code by returning condition directly, also use single quotes for stringsas it follows correct code style.

File: fictadvisor-api/src/v2/api/services/ScheduleService.ts [hunk 2]
```diff
@@ -670,6 +671,21 @@ export class ScheduleService {
...
+    await this.disciplineRepository.updateById(disciplineId, {
+      disciplineTypes: {
+        update: {
+          where: {
+            id: disciplineType.id,
+          },
+          data: {
+            disciplineTeacherRoles: {
+              deleteMany: {},
+            }
```
Comment (dmykyr) [inline fictadvisor-api/src/v2/api/services/ScheduleService.ts:683]: Add trailing commas

**Review by dmykyr — CHANGES_REQUESTED** [review]

**Review by dmykyr — APPROVED** [review]
