### PR TITLE
bug #156: reset complaint form

### LINKED ISSUE #156: [BUG] The same responses in complaining forms
**Steps to reproduce**
1. Go to https://dev.fictadvisor.com/teachers/5c47fe6d-df83-4222-bfa8-46f32104928f
2. Click on button "Залишити скаргу"
3. FIll in fields
4. Click on "Лишити скаргу"
5. Pay attention to answers in request payload
6. Click on button "Залишити скаргу"
7. Pay attention to field you`ve filled earlier
8.  Click on button "Залишити скаргу"
9. Pay attention to answers in request payload
**Actual result:**

https://github.com/fictadvisor/fictadvisor/assets/100213341/6bafec5f-8804-43e4-aa55-6b84f6976f33

**Expected result:**
Form result are not saved after sending one form
**Environment:**
-deploy: dev
-url: https://dev.fictadvisor.com/teachers/5c47fe6d-df83-4222-bfa8-46f32104928f
-OS: windows 10
-browser: Google Chrome 116.0.5845.141

### PR DESCRIPTION
**Pull request by Arsaide**
- added use resetForm function from Formik

closes #156

### CODE REVIEW

**Review by M-Rybalko — APPROVED** [review]

File: fictadvisor-web/src/components/pages/personal-teacher-page/personal-teacher-tabs/components/complaint-popup/ComplaintPopup.tsx [hunk 1]
```diff
@@ -34,7 +34,10 @@ const ComplaintPopup: FC<ComplaintPopupProps> = ({
   const toast = useToast();
   const isTablet = useMediaQuery(theme.breakpoints.down('tablet'));
 
-  const handleSubmit = async (data: Complaint) => {
+  const handleSubmit = async (
+    data: Complaint,
+    { resetForm }: { resetForm: () => void },
```
Comment (Markusplay) [inline fictadvisor-web/src/components/pages/personal-teacher-page/personal-teacher-tabs/components/complaint-popup/ComplaintPopup.tsx:39]: why not resetForm: ()=>void

**Review by Markusplay — CHANGES_REQUESTED** [review]

**Review by M-Rybalko — APPROVED** [review]

**Review by Markusplay — APPROVED** [review]

**Review by Markusplay — APPROVED** [review]
