### PR TITLE
bug #473 fixed field for entering the group name and dropdown menu

### LINKED ISSUE #473: [BUG] The field for entering the group name is updated to show the old text in the schedule page after you enter the new one.
**Preconditions:**
Log in to your student account.

**Steps to reproduce**
1. Go to the schedule page.
2. Choose a schedule for any group.
3. Reload the page.
4. Enter the name of another group in the group selection field.
5. Pay attention to the field for entering the group name.

**Actual result:**
The field for entering the group name is updated to show the old text after you enter the new one.

**Expected result:**
The new text is entered and saved in the group name field. 

**Environment:**
-deploy: prod
-url: https://ficeadvisor.com/
-OS: Windows
-browser: Google Chrome 128.0.6613.86 

https://github.com/user-attachments/assets/00c25829-c108-4cb3-8672-1f3e2a6f28fd

### PR DESCRIPTION
**Pull request by Moriartymath**
closes #473

### CODE REVIEW

File: fictadvisor-web/src/components/common/ui/form/dropdown/Dropdown.tsx [hunk 1]
```diff
@@ -88,7 +93,7 @@ const Dropdown: FC<DropdownProps> = ({
               sx={inputSx ?? styles.input(dropdownState, size)}
               placeholder={placeholder}
               disabled={isDisabled}
-              onChange={onInputChange}
+              onChange={ev => handleInputChange(ev.target.value)}
```
Comment (sifes) [inline fictadvisor-web/src/components/common/ui/form/dropdown/Dropdown.tsx:96]: do not use "ev", use just e or event instead

File: fictadvisor-web/src/components/common/ui/form/dropdown/Dropdown.tsx [hunk 2]
```diff
@@ -50,11 +52,15 @@ const Dropdown: FC<DropdownProps> = ({
...
+    setIsEditing(true);
+    onInputChange(text);
+  };
 
-  const selectedValue: DropDownOption | null = useMemo(
-    () => options.find(({ id }) => id === value) || null,
-    [options, value],
-  );
+  const selectedValue: DropDownOption | null = useMemo(() => {
+    if (isEditing) return { label: value } as DropDownOption;
```
Comment (sifes) [inline fictadvisor-web/src/components/common/ui/form/dropdown/Dropdown.tsx:61]: use ternary operator instead of if else and remove return (use arrow function one line return)

File: fictadvisor-web/src/app/(main)/schedule/schedule-page/calendar-section/components/groups-dropdown/GroupsDropDown.tsx [hunk 3]
```diff
@@ -14,9 +15,20 @@ export const GroupsDropDown: FC<DropDownSectionProps> = ({ groups }) => {
...
   }));
   const setGroupId = useSetGroupId();
+  const [inputGroupId, setInputGroupId] = useState('');
+  const [isEditing, setIsEditing] = useState(false);
+
+  useEffect(() => {
+    setInputGroupId(groups.find(({ id }) => id === groupId)?.code || '');
+  }, [groupId, setInputGroupId]);
+
+  function handleInput(text: string) {
```
Comment (sifes) [inline fictadvisor-web/src/app/(main)/schedule/schedule-page/calendar-section/components/groups-dropdown/GroupsDropDown.tsx:25]: Instead of that you could just use the groupId from localStorage or whatever place it is saved as a initialValue, without need to add a props to COMMON ui component

Comment (sifes) [reply fictadvisor-web/src/app/(main)/schedule/schedule-page/calendar-section/components/groups-dropdown/GroupsDropDown.tsx:25]: alternatively, you could implement a debounce function to handle input changes, allowing the user to enter a value and only saving groupId after a delay

**Review by sifes — CHANGES_REQUESTED** [review]

File: fictadvisor-web/src/app/(main)/schedule/schedule-page/calendar-section/components/groups-dropdown/GroupsDropDown.tsx [hunk 4]
```diff
@@ -32,7 +44,9 @@ export const GroupsDropDown: FC<DropDownSectionProps> = ({ groups }) => {
         useSchedule.setState(state => ({ isNewEventAdded: false }));
         setGroupId(id);
       }}
-      value={groupId}
+      onInputChange={handleInput}
+      setIsEditing={setIsEditing}
+      value={isEditing ? inputGroupId : groupId}
```
Comment (sifes) [inline fictadvisor-web/src/app/(main)/schedule/schedule-page/calendar-section/components/groups-dropdown/GroupsDropDown.tsx:49]: ось тут ти використовуєш isEditing, тобі не це потрібно, ти можеш просто передавати groupId в стейт вище (inputGroupId) як початкове значення і позбутись isEditing

File: fictadvisor-web/src/components/common/ui/form/dropdown/Dropdown.tsx [hunk 5]
```diff
@@ -16,7 +16,7 @@ import Option from './components/option';
 import * as styles from './Dropdown.styles';
 import { DropDownOption, DropdownProps } from './types';
 
-const Dropdown: FC<DropdownProps> = ({
+const Dropdown: FC<DropdownProps> = memo(function Dropdown({
```
Comment (sifes) [inline fictadvisor-web/src/components/common/ui/form/dropdown/Dropdown.tsx:19]: why are you memoizing component

File: fictadvisor-web/src/app/(main)/schedule/schedule-page/calendar-section/components/groups-dropdown/GroupsDropDown.tsx [hunk 6]
```diff
@@ -15,23 +16,30 @@ export const GroupsDropDown: FC<DropDownSectionProps> = ({ groups }) => {
...
   const setGroupId = useSetGroupId();
 
+  const memoGroups = useMemo(() => {
+    return groups
+      ? groups?.map(group => ({
+          id: group.id,
+          label: group.code,
+        }))
+      : [];
+  }, [groups.length]);
```
Comment (sifes) [inline fictadvisor-web/src/app/(main)/schedule/schedule-page/calendar-section/components/groups-dropdown/GroupsDropDown.tsx:26]: just groups instead of [groups.length], is inside of the useMemo hook you check for existing a groups

File: fictadvisor-web/src/app/(main)/schedule/schedule-page/calendar-section/components/groups-dropdown/GroupsDropDown.tsx [hunk 7]
```diff
@@ -15,23 +16,30 @@ export const GroupsDropDown: FC<DropDownSectionProps> = ({ groups }) => {
   }));
   const setGroupId = useSetGroupId();
 
+  const memoGroups = useMemo(() => {
+    return groups
```
Comment (sifes) [inline fictadvisor-web/src/app/(main)/schedule/schedule-page/calendar-section/components/groups-dropdown/GroupsDropDown.tsx:20]: remove curly braces and return statement

File: fictadvisor-web/src/app/(main)/schedule/schedule-page/calendar-section/components/groups-dropdown/GroupsDropDown.tsx [hunk 8]
```diff
@@ -15,23 +16,30 @@ export const GroupsDropDown: FC<DropDownSectionProps> = ({ groups }) => {
...
+      ? groups?.map(group => ({
+          id: group.id,
+          label: group.code,
+        }))
+      : [];
+  }, [groups.length]);
+
+  const onChangeMemo = useCallback(
+    (id: string) => {
+      useSchedule.setState(state => ({ isNewEventAdded: false }));
```
Comment (sifes) [inline fictadvisor-web/src/app/(main)/schedule/schedule-page/calendar-section/components/groups-dropdown/GroupsDropDown.tsx:30]: shouldn`t you call it like  (state => ({ ...state, isNewEventAdded: false }));?

**Review by sifes — CHANGES_REQUESTED** [review]

File: fictadvisor-web/src/components/common/ui/form/dropdown/Dropdown.tsx (hunk 5 above)
Comment (Moriartymath) [reply fictadvisor-web/src/components/common/ui/form/dropdown/Dropdown.tsx:19]: Because it get rid of unnecessary re-rendenders, and solve the problem of dropdown menu

File: fictadvisor-web/src/app/(main)/schedule/schedule-page/calendar-section/components/groups-dropdown/GroupsDropDown.tsx (hunk 6 above)
Comment (Moriartymath) [reply fictadvisor-web/src/app/(main)/schedule/schedule-page/calendar-section/components/groups-dropdown/GroupsDropDown.tsx:26]: groups is an object, so every time it gets recreated a new object will be returned from useMemo, and so it will create the same issue with re-rendenders of DropDown component

File: fictadvisor-web/src/app/(main)/schedule/schedule-page/calendar-section/components/groups-dropdown/GroupsDropDown.tsx (hunk 8 above)
Comment (Moriartymath) [reply fictadvisor-web/src/app/(main)/schedule/schedule-page/calendar-section/components/groups-dropdown/GroupsDropDown.tsx:30]: This is not my changes, someone did this in this way

File: fictadvisor-web/src/app/(main)/schedule/schedule-page/calendar-section/components/groups-dropdown/GroupsDropDown.tsx (hunk 6 above)
Comment (sifes) [reply fictadvisor-web/src/app/(main)/schedule/schedule-page/calendar-section/components/groups-dropdown/GroupsDropDown.tsx]: inside that hook you check for existing a groups (groups ? ... : ...) so wont there be a problem like ```cannot read properties of undefined. reading property "length"``` because groups object is undefined?

Comment (Moriartymath) [reply fictadvisor-web/src/app/(main)/schedule/schedule-page/calendar-section/components/groups-dropdown/GroupsDropDown.tsx]: image
It's not marked it type of this variable. So i cannot be undefined

Comment (sifes) [reply fictadvisor-web/src/app/(main)/schedule/schedule-page/calendar-section/components/groups-dropdown/GroupsDropDown.tsx]: if so, then check for groups.length inside that hook, because now it doesnt make any sense

File: fictadvisor-web/src/app/(main)/schedule/schedule-page/calendar-section/components/groups-dropdown/GroupsDropDown.tsx [hunk 9]
```diff
@@ -15,23 +16,32 @@ export const GroupsDropDown: FC<DropDownSectionProps> = ({ groups }) => {
   }));
   const setGroupId = useSetGroupId();
 
+  const memoGroups = useMemo(
+    () =>
+      groups.length
+        ? groups?.map(group => ({
```
Comment (sifes) [inline fictadvisor-web/src/app/(main)/schedule/schedule-page/calendar-section/components/groups-dropdown/GroupsDropDown.tsx:22]: so, the groups cannot be undefined or any falsy value, why do you check groups?.map

**Review by sifes — CHANGES_REQUESTED** [review]

**Review by sifes — APPROVED** [review]
