### PR TITLE
bug #210: fixed 'download more' button

### LINKED ISSUE #210: [BUG] The 'Download more' button appears when there are no other teachers during the search
**Preconditions:**
User is authorised.
**Steps to reproduce**
1. Go to Teachers page.
2. Enter the teacher's last name in the search field.
3. Pay attention to 'Download more' button.

**Actual result:**
The 'Download more' button appears when there are no other teachers during the search.
Знімок екрана 2024-02-01 о 23 54 05

**Expected result:**
The "Download More" button does not appear if there are no other teachers during the search.

Environment:
-deploy: prod
-url: https://fictadvisor.com/teachers
-OS: macOS Monterey 12.7.2
-browser: Safari 17.2.1 (17617.1.17.11.12, 17617)

### PR DESCRIPTION
**Pull request by Arsaide**
- fixed display button 'download more'

closes #210

### CODE REVIEW

File: fictadvisor-web/src/components/pages/search-pages/teacher-search/TeacherSearchPage.tsx [hunk 1]
```diff
@@ -61,7 +62,11 @@ export const TeacherSearchPage = () => {
           return TeacherAPI.getPage(queryObj, PAGE_SIZE, curPage + 1);
         }
       },
-      { keepPreviousData: true, refetchOnWindowFocus: false },
+      {
+        keepPreviousData: true,
+        refetchOnWindowFocus: false,
+        onError: error => console.log(error),
```
Comment (M-Rybalko) [inline fictadvisor-web/src/components/pages/search-pages/teacher-search/TeacherSearchPage.tsx:68]: Remove console.log (if necessary, use toast errors)

File: fictadvisor-web/src/components/pages/search-pages/teacher-search/TeacherSearchPage.tsx [hunk 2]
```diff
@@ -70,9 +75,15 @@ export const TeacherSearchPage = () => {
   };
 
   useEffect(() => {
-    void refetch();
+    refetch();
   }, [queryObj, curPage, refetch, reloadTeachers]);
 
+  if (isLoading) {
+    return <div>qwe</div>;
```
Comment (M-Rybalko) [inline fictadvisor-web/src/components/pages/search-pages/teacher-search/TeacherSearchPage.tsx:82]: Add text which makes sense

File: fictadvisor-web/src/components/pages/search-pages/teacher-search/TeacherSearchPage.tsx [hunk 3]
```diff
@@ -70,9 +75,15 @@ export const TeacherSearchPage = () => {
...
+  }
+
+  console.log();
```
Comment (M-Rybalko) [inline fictadvisor-web/src/components/pages/search-pages/teacher-search/TeacherSearchPage.tsx:85]: Remove it

**Review by M-Rybalko — CHANGES_REQUESTED** [review]

**Review by M-Rybalko — APPROVED** [review]
