### PR TITLE
bug #190: changed disciplineType to eventType

### LINKED ISSUE #190: [BUG] 🛠️ Change `disciplineType` to `eventType`
This task is related to both frontend and backend repos, 

`backend`

- [ ] change return type on `/v2/schedule/groups/{groupId}/general` and `/v2/schedule/groups/{groupId}/events` from
```ts
   "disciplineType": {
        "id": "string",
        "disciplineId": "string",
        "name": "LECTURE"
      }
```
to 
```ts
   "eventType": EVENT_TYPE
```

`frontend` 

- [ ] change all the places where `disciplineType.name`  is used to `eventType`
- [ ] make sure to change all the places and namings from disciplineType to eventType
- [ ] change manually written types used in `generics` for`ScheduleApi` to types from backend

### PR DESCRIPTION
**Pull request by ShavuhaS**
frontend
- changed all the places where disciplineType.name is used to eventType
- changed all appearances of disciplineType to eventType
- changed manually written types used in `generics` for ScheduleApi to types from backend

backend
- changed response fields from disciplineType to eventType on /schedule/groups/{groupId}/*

closes #190

### CODE REVIEW

**Review by fokaaas — DISMISSED** [review]

File: fictadvisor-web/src/components/pages/schedule-page/schedule-event-edit-section/schedule-form/ScheduleEventForm.tsx [hunk 1]
```diff
@@ -85,13 +85,11 @@ export const ScheduleEventForm: FC<ScheduleEventFormProps> = ({
             <Box sx={styles.content}>
               <Typography variant="body1Medium">Тип</Typography>
               <ScheduleFormikDropdown
-                name={'disciplineType'}
+                name={'eventType'}
```
Comment (igaryakqwe) [inline fictadvisor-web/src/components/pages/schedule-page/schedule-event-edit-section/schedule-form/ScheduleEventForm.tsx:88]: don't use curly braces

**Review by igaryakqwe — APPROVED** [review]

**Review by igaryakqwe — APPROVED** [review]
