### PR TITLE
bug #549: fixed groups creating by parser

### LINKED ISSUE #549: [BUG] parser groups creating bug
At the begining of this studying year we have some bug in parser, which caused incorrect creating of groups. Group roles were not created. Your task is to find and fix this bug

### PR DESCRIPTION
**Pull request by bohdanbulakh**
- found and fixed bug with invalid date
- added creating of group roles in campus parser

closes #549

### CODE REVIEW

File: fictadvisor-api/src/v2/api/services/GroupService.ts [hunk 1]
```diff
@@ -291,11 +318,7 @@ export class GroupService {
       },
     });
 
-    if (!captain) {
-      throw new AbsenceOfCaptainException();
-    }
-
-    return captain.user;
+    return captain?.user;
```
Comment (VlO-OlV) [inline fictadvisor-api/src/v2/api/services/GroupService.ts:321]: This change causes TypeError on groups/:groupId/captain Get endpoint. If group has no captain, undefined is passed to userMapper.getUser method. So, for example, create a separate method in GroupService with this validation for handling that route.

File: fictadvisor-api/src/v2/api/services/GroupService.ts [hunk 2]
```diff
@@ -291,11 +318,7 @@ export class GroupService {
       },
     });
 
-    if (!captain) {
-      throw new AbsenceOfCaptainException();
```
Comment (VlO-OlV) [inline fictadvisor-api/src/v2/api/services/GroupService.ts:295]: Remove unused import

**Review by VlO-OlV — CHANGES_REQUESTED** [review]

**Review by VlO-OlV — APPROVED** [review]
