### PR TITLE
 bug #176: fixed telegram auth bug

### LINKED ISSUE #176: [BUG] User authorization with Telegram is not working
**Preconditions:**
- The user is not authorized.

**Steps to reproduce**
1. Go to the FICT Advisor login page.
2. Click on the 'Увійти за допомогою Telegram' button
3. Pay attention to the page.

**Actual result:**
The user is redirected to the FICT Advisor bot and is not authorized in the account.

https://github.com/fictadvisor/fictadvisor/assets/111194749/059cda97-3525-46f5-b54c-45a5eec8c4b4

**Expected result:**
The user is authorized in the account.

**Environment:**
-deploy: prod
-url: https://fictadvisor.com/login
-OS: Windows 10
-browser: Google Chrome 116.0.5845.141

### PR DESCRIPTION
**Pull request by M-Rybalko**
- fixed telegram auth bug

closes #176

### CODE REVIEW

File: fictadvisor-web/src/lib/services/telegram/TelegramService.ts [hunk 1]
```diff
@@ -46,10 +35,10 @@ class TelegramService {
       StorageUtil.setTokens(accessToken, refreshToken);
       return true;
     } catch (e) {
+      console.log(e);
```
Comment (Markusplay) [inline fictadvisor-web/src/lib/services/telegram/TelegramService.ts:38]: kill it

**Review by Markusplay — CHANGES_REQUESTED** [review]

**Review by Markusplay — APPROVED** [review]
