### PR TITLE
enhancement #316: rewrote main page to the server component

### LINKED ISSUE #141: [BUG] Displacement of student resources on the main page
**Preconditions:**
1. The user is authorized.
**Steps to reproduce**
1. Go to 'Main page'.
2. Click on 'Burger menu' and went to any page (for example, 'Schedule').
3. The user back on the main page.
4. Pay attention to 'Student Resources' (has moved to the right).

**Actual result:**
Moving 'Student Resources' on the main page after switching to another page (for example, 'Schedule')
Знімок екрана 2024-01-13 о 20 37 47

**Expected result:**
'Student Resources' does not move on the main page when navigating to another page.

**Environment:**
-deploy: dev
-url: http://dev.fictadvisor.com
-OS: macOS Monterey 12.7.2
-browser: Safari 17.2.1 (17617.1.17.11.12, 17617)

### LINKED ISSUE #316: Move `Main` to server components
With the introduction [`React Server Components`](https://nextjs.org/docs/app/building-your-application/rendering/server-components) nextjs implemented this in their newer versions and has kinda shifted their paradigm

Why server components are needed?
Let's look at a brief example: 
1. Open a main [page](https://ficeadvisor.com/) 
2. Press Ctrl + U to open page source
3. Try to find `офіційний сайт Студради ФІОТ. Опитування про викладачів, багатофункціональний розклад,`
4. You cannot find it, this is how browser crawlers see this page, they do not index main page as they could have

We can find page by this text anyways
image

Why this is a case?
That's beacuse of the this block of [code](https://github.com/fictadvisor/fictadvisor/blob/c5ec34afc25e3f31be662e916afa15a75969c607/fictadvisor-web/src/app/page.tsx#L6) 
```ts
export const metadata: Metadata = {
  title: 'FICE Advisor',
  description:
    'Зустрічай FICE Advisor — офіційний сайт Студради ФІОТ. Опитування про викладачів, багатофункціональний розклад, керування групою, набори в наше активне ком’юніті, розіграш шар та інші інструменти — шукай саме тут!',
  openGraph: {
    title: 'FICE Advisor',
    description:
      'Зустрічай FICE Advisor — офіційний сайт Студради ФІОТ. Опитування про викладачів, багатофункціональний розклад, керування групою, набори в наше активне ком’юніті, розіграш шар та інші інструменти — шукай саме тут!',
  },
};
```

We could even make a seo better once the text was included in the source

## The task
In this task you have to rewrite main page to server components, after finishing the task, make sure that the correct text is visible in page source.

### PR DESCRIPTION
**Pull request by namanica**
- changed data fetching format
- changed styles
- added buttons

closes #316, closes #141

### CODE REVIEW

File: fictadvisor-web/src/app/main-page/MainPage.tsx [hunk 1]
```diff
@@ -0,0 +1,87 @@
...
+                  text={name}
+                  image={imageLink}
+                  href={link}
+                />
+              ))}
+            </Box>
+          </Box>
+        </Box>
+      </Box>
+    </PageLayout>
```
Comment (igaryakqwe) [inline fictadvisor-web/src/app/main-page/MainPage.tsx:83]: move this part to page.tsx and delete this file then

File: fictadvisor-web/src/app/page.tsx [hunk 2]
```diff
@@ -1,71 +1,38 @@
...
 }
 
+const pageTextsKeys = [
+  'mainpage_title',
+  'mainpage_description',
+  'mainpage_primary',
+  'mainpage_secondary',
+  'mainpage_studentresources_title',
+];
+
```
Comment (igaryakqwe) [inline fictadvisor-web/src/app/page.tsx:24]: create constants directory and put this object there

**Review by igaryakqwe — CHANGES_REQUESTED** [review]

**Review by igaryakqwe — APPROVED** [review]
