### PR TITLE
bug #542: fixed small bugs

### LINKED ISSUE #542: [BUG] small bugs
**bug 1:**
**Steps to reproduce**
1. Go to "Зареєструватися"
2. Fill all fields
3. Click button "Зареєструватись"

**Actual result:**
Трапилась помилка
Avatar must be a string

**Expected result:**
Successful registration

**bug 2:**
**Preconditions:**
- user didn't select selective disciplines

**Steps to reproduce**
1. Go to 'Мої вибіркові'
2. Click on this button: 
Screenshot_20241203_153254

**Actual result:**
Screenshot_20241203_153411
Open requests tab in developer options of your browser and you will see this:
Screenshot_20241203_153630

**Expected result:**
list with selective disciplines

**bug 3:**
add swagger body to login endpoint

### PR DESCRIPTION
**Pull request by bohdanbulakh**
- fixed discipline selecting
- added api body for login endpoint
- fixed registration error
- found and fixed axios exception bug

closes #542

### CODE REVIEW

File: utils/src/requests/UserDTO.ts [hunk 1]
```diff
@@ -38,13 +38,14 @@ export class UserDTO {
   @ApiProperty({
```
Comment (VlO-OlV) [inline utils/src/requests/UserDTO.ts:38]: Replace with ApiPropertyOptional decorator

File: utils/src/requests/UserDTO.ts [hunk 2]
```diff
@@ -38,13 +38,14 @@ export class UserDTO {
...
     description: 'User\'s avatar url',
   })
+  @IsOptional()
   @IsString(validationOptionsMsg('Avatar must be string'))
-  avatar?: string;
+    avatar?: string;
 
   @ApiProperty({
```
Comment (VlO-OlV) [inline utils/src/requests/UserDTO.ts:45]: Replace with ApiPropertyOptional decorator

**Review by VlO-OlV — CHANGES_REQUESTED** [review]

**Review by VlO-OlV — APPROVED** [review]
