### PR TITLE
documentation #56: updated swagger for users

### LINKED ISSUE #56: [DOC] Update Swagger for User
We are updating the documentation for all endpoints and adding more _description and details_. 

One of the main controllers is User. You should update the documentation according to the **pattern** below:
```ts
  @ApiBearerAuth()
  @ApiOkResponse({
    type: DisciplineTeachersResponse,
  })
  @ApiBadRequestResponse({
    description: `\n
    InvalidQueryException:
      Type of discipline must be a field of enum
    InvalidDisciplineIdException:
      Discipline with such id is not found`,
  })
  @ApiUnauthorizedResponse({
    description: `\n
    UnauthorizedException:
      Unauthorized`,
  })
  @ApiForbiddenResponse({
    description: `\n
    NoPermissionException:
      You do not have permission to perform this action`,
  })
  @ApiParam({
    name: 'disciplineId',
    required: true,
    description: 'Id of certain discipline',
  })
  @ApiQuery({
    name: 'disciplineType',
    required: true,
    enum: DisciplineTypeEnum,
    description: 'Discipline type of some discipline',
  })
  @ApiEndpoint({
    summary: 'Receive teachers by discipline',
    permissions: PERMISSION.GROUPS_$GROUPID_DISCIPLINES_TEACHERS_GET,
  })
  @Get('/:disciplineId/teachers')
  async getAllByDiscipline (
    @Param('disciplineId', DisciplineByIdPipe) disciplineId: string,
    @Query('disciplineType') disciplineType: DisciplineTypeEnum
  ) {
    const teachers = await this.disciplineService.getTeachers(disciplineId, disciplineType);
    return { teachers };
  }
```
**Structure:**
- auth (if needed)
- ok response
- client errors
- params/query description
- access (if needed)

You should also add **field description** in the bady or response.
Add **summary** to endpoints.
Set **default values** for the optional fields

image

_Buena suerte_

[Our Swagger](https://apidev.fictadvisor.com/api)
[Doc](https://docs.nestjs.com/openapi/introduction)

### PR DESCRIPTION
**Pull request by kytaets**
- updated linkTelegram endpoint
- updated uploadAvatar endpoint
- updated deleteAvatar endpoint
- updated changeGroup endpoint

closes #56

### CODE REVIEW

File: fictadvisor-api/src/v2/api/controllers/UserController.ts [hunk 1]
```diff
@@ -812,6 +812,34 @@ export class UserController {
...
+  @ApiBadRequestResponse({
+    description: `\n
+    InvalidEntityIdException:
+      User with such id is not found`,
+  })
+  @ApiForbiddenResponse({
+    description: `\n
+    NoPermissionException:
+      You do not have permission to perform this action`,
+  })
```
Comment (illiakroshka) [inline fictadvisor-api/src/v2/api/controllers/UserController.ts:828]: Add Telegram DTO Exceptions and InvalidTelegramCredentialsException with DuplicateTelegramIdException

File: fictadvisor-api/src/v2/api/controllers/UserController.ts [hunk 2]
```diff
@@ -812,6 +812,34 @@ export class UserController {
...
+  @ApiParam({
+    name: 'userId',
+    required: true,
+    description: 'Id of a user',
+  })
+  @ApiParam({
+    name: 'telegram',
+    required: true,
+    description: 'Telegram link of a user',
+  })
```
Comment (illiakroshka) [inline fictadvisor-api/src/v2/api/controllers/UserController.ts:838]: This endpoint takes only 1 parameter userId, telegram is not parameter it is a body

File: fictadvisor-api/src/v2/api/controllers/UserController.ts [hunk 3]
```diff
@@ -812,6 +812,34 @@ export class UserController {
   }
 
   @Access(PERMISSION.USERS_$USERID_TELEGRAM_LINK)
```
Comment (illiakroshka) [inline fictadvisor-api/src/v2/api/controllers/UserController.ts:814]: Add ApiBearerAuth() decorator because this endppoint has auth

File: fictadvisor-api/src/v2/api/controllers/UserController.ts [hunk 4]
```diff
@@ -893,6 +922,20 @@ export class UserController {
     NoPermissionException:
```
Comment (illiakroshka) [inline fictadvisor-api/src/v2/api/controllers/UserController.ts:922]: Here also remove Access decorator

File: fictadvisor-api/src/v2/api/controllers/UserController.ts [hunk 5]
```diff
@@ -893,6 +922,20 @@ export class UserController {
...
+  @ApiParam({
+    name: 'file',
+    required: true,
+    description: 'File of a user\'s avatar',
+  })
+  @ApiParam({
+    name: 'userId',
+    required: true,
+    description: 'Id of a user',
+  })
```
Comment (illiakroshka) [inline fictadvisor-api/src/v2/api/controllers/UserController.ts:934]: This endpoint takes only 1 parameter userId

File: fictadvisor-api/src/v2/api/controllers/UserController.ts [hunk 6]
```diff
@@ -893,6 +922,20 @@ export class UserController {
...
+  @ApiEndpoint({
+    summary: 'Uploads user\'s avatar',
+    permissions: PERMISSION.USERS_$USERID_UPDATE,
+  })
   @UseInterceptors(FileInterceptor('avatar'))
```
Comment (illiakroshka) [inline fictadvisor-api/src/v2/api/controllers/UserController.ts:939]: Place swagger utils in the corect order (watch your issue)

File: fictadvisor-api/src/v2/api/controllers/UserController.ts [hunk 7]
```diff
@@ -923,6 +967,15 @@ export class UserController {
     NoPermissionException:
       You do not have permission to perform this action`,
   })
```
Comment (illiakroshka) [inline fictadvisor-api/src/v2/api/controllers/UserController.ts:969]: Remove Access decorator

File: fictadvisor-api/src/v2/api/controllers/UserController.ts [hunk 8]
```diff
@@ -923,6 +967,15 @@ export class UserController {
...
+  @ApiParam({
+    name: 'userId',
+    required: true,
+    description: 'Id of a user',
+  })
+  @ApiEndpoint({
+    summary: 'Deletes user\'s avatar',
+    permissions: PERMISSION.USERS_$USERID_DELETE,
+  })
```
Comment (illiakroshka) [inline fictadvisor-api/src/v2/api/controllers/UserController.ts:978]: Here also place swagger utils in the correct order

File: fictadvisor-api/src/v2/api/controllers/UserController.ts [hunk 9]
```diff
@@ -933,6 +986,7 @@ export class UserController {
   @ApiBearerAuth()
   @ApiOkResponse({
     type: RemainingSelectiveResponse,
+    description: 'Deleted user\'s avatar',
```
Comment (illiakroshka) [inline fictadvisor-api/src/v2/api/controllers/UserController.ts:989]: Wrong description, it's another endpoint 😅

File: fictadvisor-api/src/v2/api/controllers/UserController.ts [hunk 10]
```diff
@@ -1067,6 +1122,20 @@ export class UserController {
                   NotApprovedException: Student is not approved
                   NoPermissionException: You do not have permission to perform this action`,
   })
```
Comment (illiakroshka) [inline fictadvisor-api/src/v2/api/controllers/UserController.ts:1124]: Format error massages by code style 
see: https://gist.github.com/Hahhhayam/43197ad702006f475eb8d97fb8c08814

File: fictadvisor-api/src/v2/api/controllers/UserController.ts [hunk 11]
```diff
@@ -1056,6 +1110,7 @@ export class UserController {
   @Patch('/:userId/group/:groupId')
```
Comment (illiakroshka) [inline fictadvisor-api/src/v2/api/controllers/UserController.ts:1110]: Remove Access decorator and place in the correct order

File: fictadvisor-api/src/v2/api/dtos/TelegramDTO.ts [hunk 12]
```diff
@@ -44,4 +44,5 @@ export class TelegramDTO {
   })
   @IsNotEmpty(validationOptionsMsg('Username cannot be empty'))
     username: string;
-}
\ No newline at end of file
+
```
Comment (illiakroshka) [inline fictadvisor-api/src/v2/api/dtos/TelegramDTO.ts:47]: unnecessary enter

File: fictadvisor-api/src/v2/api/controllers/UserController.ts [hunk 13]
```diff
@@ -1067,6 +1122,20 @@ export class UserController {
...
+  })
+  @ApiParam({
+    name: 'groupId',
+    required: true,
+    description: 'Id of a group',
+  })
+  @ApiEndpoint({
+    summary: 'Changes user\'s group',
+    permissions: PERMISSION.USERS_GROUPS_SWITCH,
+  })
```
Comment (illiakroshka) [inline fictadvisor-api/src/v2/api/controllers/UserController.ts:1138]: Add ApiBearerAuth for this endpoint

Comment (illiakroshka) [inline fictadvisor-api/src/v2/api/controllers/UserController.ts:1138]: Add Unauthorized Exception and no permission exception

**Review by illiakroshka — CHANGES_REQUESTED** [review]

**Comment by illiakroshka** [comment]
image
You use RoleWithStudentResponse in the FullStudentsResponse, add description for the fields in it (studentId, roleId, role)

**Review by illiakroshka — APPROVED** [review]
