### PR TITLE
bug #23: other event fields are not visible

### LINKED ISSUE #23: [BUG] Fix bugs on subject card with type "Інша подія" after clicking on it
**Bug №1**

**Summary:** Lecturer and discipline description are visible on subject card with type "Інша подія" after clicking on it.

**Preconditions:** User is authorized, member of a group and has a permission to edit the schedule, event with type "Інша подія" is added to schedule.

**Steps to reproduce**
1. Go to Schedule page.
2. Click on event with type "Інша подія".
3. Pay attention to the "Викладач" and "Про дисципліну" fields.

**Actual result:** "Викладач" and "Про дисципліну" fields are visible.

Image

**Expected result:** "Викладач" and "Про дисципліну" fields are invisible ([figma](https://www.figma.com/file/FHBiKogMc9VzGWojaQxA9c/%F0%9F%92%96fictadvisor?type=design&node-id=242%3A2&mode=design&t=4RhzSSDWcm5ELuVF-1)).

Image

**Bug №2**

**Summary:** Event type is thrown off on subject card with type "Інша подія" while editing it.

**Preconditions:** User is authorized, member of a group and has a permission to edit the schedule, event with type "Інша подія" is added to schedule.

**Steps to reproduce**
1. Go to Schedule page.
2. Click on event with type "Інша подія".
3. Click on change event button.
4. Pay attention to the "Тип" field.

**Actual result:** Event type is thrown off.

https://github.com/fictadvisor/fictadvisor-web/assets/62239358/f1d5f88c-82dc-4f7f-b1a0-acb231d2adad

Image

**Expected result:** Event type is saved and displayed as "Інша подія".

Image

**Bug №3**

**Summary:** Changes of event with type "Інша подія" can't be saved on Schedule page after editing.

**Preconditions:** User is authorized, member of a group and has a permission to edit the schedule, event with type "Інша подія" is added to schedule.

**Steps to reproduce**
1. Go to Schedule page.
2. Click on event with type "Інша подія".
3. Click on change event button.
4. Change any information (except of event type).
5. Click on the save button.
6. Pay attention to the event.

**Actual result:** Changes in event with type "Інша подія" can't be saved.

https://github.com/fictadvisor/fictadvisor-web/assets/62239358/e86dcd33-4ff9-403d-991c-482e1ae62372

**Expected result:** Changes in event with type "Інша подія" can be saved.

**Bug №4**

**Summary:** Change of type of the existing event into "Інша подія" isn't saved on Schedule page after editing.

**Preconditions:** User is authorized, member of a group and has a permission to edit the schedule, event with any type is added to schedule.

**Steps to reproduce**
1. Go to Schedule page.
2. Click on event with type which is not "Інша подія".
3. Click on change event button.
4. Change event type.
5. Click on the save button.
6. Pay attention to the event.

**Actual result:** Change of type of the existing event into "Інша подія" isn't saved.

https://github.com/fictadvisor/fictadvisor-web/assets/62239358/640720bc-6bec-4c1d-a1e1-832b11e1b1bb

**Expected result:** Change of type of the existing event into "Інша подія" is saved.

**Environment:**
- deploy: dev;
- url: https://dev.fictadvisor.com/schedule;
- os: Windows 10;
- browser: Google Chrome 116.0.5845.163.

### PR DESCRIPTION
**Pull request by nnstsya**
- added event type checking on schedule card
- removed teacher validation on "other event" type

closes #23

### CODE REVIEW

File: fictadvisor-web/src/components/pages/schedule-page/schedule-event-edit-section/schedule-info-card/ScheduleInfoCard.tsx [hunk 1]
```diff
@@ -111,25 +111,31 @@ const ScheduleInfoCard: FC<ScheduleInfoCardProps> = ({
...
-              <Link
-                key={teacher.id}
-                href={`/teachers/${teacher.id}`}
-                text={`${teacher.firstName} ${teacher.middleName} ${teacher.lastName}`}
-                target={'_blank'}
-              />
-            ))
-          )}
-        </Box>
+        {event?.eventType !== 'OTHER' ? (
```
Comment (kujo205) [inline fictadvisor-web/src/components/pages/schedule-page/schedule-event-edit-section/schedule-info-card/ScheduleInfoCard.tsx:114]: put this in some descriptive variable like `isDisciplineRelatedEvent`,

otherwise, good job troubleshooting this giant pile of shi...

File: fictadvisor-web/src/components/pages/schedule-page/schedule-event-edit-section/schedule-form/ScheduleEventForm.tsx [hunk 2]
```diff
@@ -90,7 +90,9 @@ export const ScheduleEventForm: FC<ScheduleEventFormProps> = ({
                 options={eventTypeList}
                 placeholder={'Оберіть тип події'}
               />
-              {values.eventType && <DisciplineRelatedFields values={values} />}
+              {values.eventType !== 'OTHER' && (
+                <DisciplineRelatedFields values={values} />
+              )}
```
Comment (kujo205) [inline fictadvisor-web/src/components/pages/schedule-page/schedule-event-edit-section/schedule-form/ScheduleEventForm.tsx:95]: Here as well, since it's repeated 2 times

**Review by kujo205 — CHANGES_REQUESTED** [review]
Good job!

**Review by kujo205 — APPROVED** [review]
Good!

**Review by igaryakqwe — APPROVED** [review]
