### PR TITLE
bugfix #251, #250: fixed editing not verified user on admin panel

### LINKED ISSUE #250: [BUG] User's actual data is not displayed on the User admin tab after entering the editing mode
**Preconditions:** User is authorized as admin.

**Steps to reproduce**
1. Open the https://dev.fictadvisor.com/admin.
2. Go to the users page.
3. Choose a user and click on the 'Редагувати' button.
4. Pay attention to the field's values.

**Actual result:** User's actual data is not displayed on the User admin tab after entering the editing mode.

Image

**Expected result:** User's actual data is displayed in the fields on the User admin tab after entering the editing mode.

Image

**Environment:**
- Deploy: dev;
- URL: https://dev.fictadvisor.com/admin/users;
- OS: Windows 10;
- Browser: Google Chrome 116.0.5845.141.

### LINKED ISSUE #251: [BUG] User data isn't saved on the User admin tab after editing or deleting user
**Preconditions:** User is authorized as admin.

**Steps to reproduce**
1. Open the https://dev.fictadvisor.com/admin.
2. Go to the users page.
3. Choose a user and click on the 'Редагувати' button.
4. Click on the 'Зберегти' or 'Видалити' button.
5. Pay attention to the error message.

**Actual result:** User data isn't saved on the User admin tab after editing or deleting user.

```ts
getUser error:
 Error
    at UserService.getUser (/app/index.js:468737:24)
```

https://github.com/fictadvisor/fictadvisor/assets/62239358/bb8138e8-be42-48bf-8fbb-bfe75fbf2c50

**Expected result:** User data is saved on the User admin tab after editing or deleting user.

**Environment:**
- Deploy: dev;
- URL: https://dev.fictadvisor.com/admin/users;
- OS: Windows 10;
- Browser: Google Chrome 116.0.5845.141.

### PR DESCRIPTION
**Pull request by hoshion**
- changed user controller to return user, not student
- remove group checking on schedule
- added new type of user (without student info)

closes #251, closes #250

### CODE REVIEW

File: fictadvisor-web/src/components/pages/schedule-page/schedule-section/components/schedule/Schedule.tsx [hunk 1]
```diff
@@ -25,6 +25,8 @@ const Schedule = () => {
     }),
   );
 
+  console.log(events);
```
Comment (sifes) [inline fictadvisor-web/src/components/pages/schedule-page/schedule-section/components/schedule/Schedule.tsx:28]: remove console.log

File: fictadvisor-web/src/types/user.ts [hunk 2]
```diff
@@ -44,3 +44,12 @@ export interface UserRemainingSelective {
 export interface UserAdmin extends Omit<User, 'firstName' | 'lastName'> {
   state: UserGroupState;
 }
+
+export interface SimplifiedUser {
```
Comment (sifes) [inline fictadvisor-web/src/types/user.ts:48]: if it is possible you should use extends User instead of simple declaration of interface

**Review by sifes — CHANGES_REQUESTED** [review]

**Review by sifes — APPROVED** [review]
