### PR TITLE
documentation #252: updated swagger for teachers 

### LINKED ISSUE #252: [DOC] Add Swagger doc for Teacher
We are updating the documentation for all endpoints and adding more _description and details_. 

One of the main controllers is Teacher. You should update the documentation according to the **pattern** below:
```ts
  @ApiBearerAuth()
  @ApiOkResponse({
    type: DisciplineTeachersResponse,
  })
  @ApiBadRequestResponse({
    description: `\n
    InvalidQueryException:
      Type of discipline must be a field of enum

    InvalidDisciplineIdException:
      Discipline with such id is not found`,
  })
  @ApiUnauthorizedResponse({
    description: `\n
    UnauthorizedException:
      Unauthorized`,
  })
  @ApiForbiddenResponse({
    description: `\n
    NoPermissionException:
      You do not have permission to perform this action`,
  })
  @ApiParam({
    name: 'disciplineId',
    required: true,
    description: 'Id of certain discipline',
  })
  @ApiQuery({
    name: 'disciplineType',
    required: true,
    enum: DisciplineTypeEnum,
    description: 'Discipline type of some discipline',
  })
 @ApiEndpoint({
    summary: 'Receive teachers by discipline',
    permissions: PERMISSION.GROUPS_$GROUPID_DISCIPLINES_TEACHERS_GET,
  })
  @Get('/:disciplineId/teachers')
  async getAllByDiscipline (
    @Param('disciplineId', DisciplineByIdPipe) disciplineId: string,
    @Query('disciplineType') disciplineType: DisciplineTypeEnum
  ) {
    const teachers = await this.disciplineService.getTeachers(disciplineId, disciplineType);
    return { teachers };
  }
```
**Structure:**
- auth (if needed)
- ok response
- client errors
- params/query description
- access (if needed)

You should also add **field description** in the bady or response.
Add **summary**  to endpoints
Set **default values** for the optional fields

image

_Buena suerte_

[Our Swagger](https://apidev.fictadvisor.com/api)
[Doc](https://docs.nestjs.com/openapi/introduction)

### PR DESCRIPTION
**Pull request by nentoday**
- updated delete endpoint
- updated getAllContacts endpoint
- updated getContact endpoint
- updated createContact endpoint
- updated updateContac endpoint
- updated deleteContact endpoint

closes #252

### CODE REVIEW

File: fictadvisor-api/src/v2/api/controllers/TeacherController.ts [hunk 1]
```diff
@@ -412,6 +438,15 @@ export class TeacherController {
     NoPermissionException:
       You do not have permission to perform this action`,
   })
+  @ApiParam({
+    name: 'teacherId',
+    required: true,
+    description: 'Id of certain teacher'
+  })
+  @ApiEndpoint({
+    summary: 'Add teacher\'s contacts',
```
Comment (bohdanbulakh) [inline fictadvisor-api/src/v2/api/controllers/TeacherController.ts:447]: - Comma after description
- Change contacts to contact in summary

File: fictadvisor-api/src/v2/api/controllers/TeacherController.ts [hunk 2]
```diff
@@ -465,27 +507,36 @@ export class TeacherController {
...
+      You do not have permission to perform this action`,
+  })
   @ApiParam({
     type: String,
     name: 'teacherId',
+    required: true,
+    description: 'Id of certain teacher'
   })
   @ApiParam({
     type: String,
```
Comment (bohdanbulakh) [inline fictadvisor-api/src/v2/api/controllers/TeacherController.ts:532]: - Comma after description
- Delete type field

**Review by bohdanbulakh — CHANGES_REQUESTED** [review]

**Review by bohdanbulakh — APPROVED** [review]
